services:
  - type: worker
    name: cat-oracle-vk
    env: python
    buildCommand: pip install -r requirements-vk.txt
    startCommand: python vk_bot.py
    pythonVersion: 3.12
    envVars:
      - key: VK_TOKEN
        sync: false
      - key: VK_GROUP_ID
        value: "190395599"
      - key: ADMIN_ID
        value: "1854526"
      - key: DATABASE_URL
        sync: false
